### PR TITLE
Update pad tests

### PR DESCRIPTION
**Pull request by wangli69087**
@BruceDai Please help review this PR. Thanks.

### CODE REVIEW

**Comment by BruceDai** [comment]
LGTM, thanks @wangli69087.

According to [WebNN API pad op explanation](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-pad), NNAPI [**PAD**](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0aaced01fc41e401b81cefcf53780558d1) and [**PAD_V2**](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0afe2c4f9e541dcc278509921fd2c8a502)  would map WebNN API **pad** op, so we could add converted pad CTS tests.

| NNAPI Op |NNAPI PAD/PAD_V2 Inputs |mapping WebNN API pad Arguments|
|----|----|----|
|PAD|0: An n-D tensor, specifying the tensor to be padded. <br>1: A 2-D Tensor of ANEURALNETWORKS_TENSOR_INT32, the paddings for each spatial dimension of the input tensor.|0 input: an MLOperand. <br>1 padding: an MLOperand.|
|PAD_V2|0: An n-D tensor, specifying the tensor to be padded.<br>1: A 2-D Tensor of ANEURALNETWORKS_TENSOR_INT32, the paddings for each spatial dimension of the input tensor.<br>2: A scalar specifying the value to use for padding input0.|0 input: an MLOperand. <br>1 padding: an MLOperand.<br>2 options: value,  with setting default "constant" model. |

@huningxin PTAL, thanks.

**Comment by huningxin** [comment]
@wangli69087 , please fix the conflicts, thanks!

**Comment by huningxin** [comment]
> @wangli69087 , please fix the conflicts, thanks!

A soft ping @wangli69087

**Comment by wangli69087** [comment]
@huningxin Please help review and merge it. Thanks.

**Comment by BruceDai** [comment]
@wangli69087 Please fix lint error, thanks.

**Comment by wangli69087** [comment]
@BruceDai This lint error is fixed. Thanks.

**Comment by BruceDai** [comment]
LGTM, thanks @wangli69087 

@huningxin Please take another look, thanks.

**Review by huningxin — APPROVED** [review]

**Pull request merged**
