### PR TITLE
Change newShape of reshape to a sequence of nullable unsigned long

### LINKED ISSUE #198: Change newShape of reshape to a sequence of nullable unsigned long
Align to latest Spec change https://github.com/webmachinelearning/webnn/pull/291.

### PR DESCRIPTION
**Pull request by BruceDai**
This pr is to fix #198. 
@huningxin @Honry PTAL, thanks.

### CODE REVIEW

**Review by Honry — APPROVED** [review]
LGTM, thanks!

**Comment by Honry** [comment]
BTW, please bump the version in package.json, for next release.

**Comment by BruceDai** [comment]
> BTW, please bump the version in package.json, for next release.

Done, please take another look, thanks.

**Comment by Honry** [comment]
Still LGTM, thanks!

**Comment by BruceDai** [comment]
@Honry Thanks for reviewing. I'm going to merge it.

**Pull request merged**
