### PR TITLE
Add SqueezeNet model test

### PR DESCRIPTION
**Pull request by huningxin**
Add the SqueezeNet model test as the initial one of [first-wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md). It is also a follow-up of [Conformance testing of ML APIs for the Web](https://github.com/w3c/machine-learning-workshop/issues/80) from the model test perspective.

Some details:
* Test both SqueezeNet 1.1 in ONNX model zoo ([link](https://github.com/onnx/models/tree/master/vision/classification/squeezenet)) and SqueezeNet 1.0 in TFLite model zoo ([link](https://www.tensorflow.org/lite/guide/hosted_models)). 
* The weights are saved in numpy files (.npy) for the sake of simplicity. 
* The test data of SqueezeNet 1.1 ONNX model is downloaded with the [model file](https://github.com/onnx/models/blob/master/vision/classification/squeezenet/model/squeezenet1.1-7.tar.gz). The test data of SqueezeNet 1.0 TFLite model is collected by using [TFLite python API](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python).

Results:
- The browser test failed by using tf.js webgpu backend. It reports the numerical difference against the expected output. You can see the failures by the [preview link](https://huningxin.github.io/webnn-polyfill/test/models.html).
- If using tf.js wasm or cpu backend, the browser test can pass.
- The node.js test (`npm run test-models`) passed as it is using tf.js cpu backend.

@anssiko @wchao1115 @pyu10055 @BruceDai , please take a look. Thanks!

Regarding to the numerical precision difference between tf.js webgl and cpu/wasm backends, @pyu10055 , do you have any insights?

### CODE REVIEW

**Review by anssiko — APPROVED** [review]
Feature suggestion (if this makes sense, open a new issue):

Could we force the polyfill to use a particular backend by e.g. passing a specific query string? E.g. https://huningxin.github.io/webnn-polyfill/test/models.html?gpu=1 to enable GPU backend, ?cpu=1 to enable CPU and so forth? This might be useful for quick debugging.

**Comment by huningxin** [comment]
> Could we force the polyfill to use a particular backend by e.g. passing a specific query string? E.g. https://huningxin.github.io/webnn-polyfill/test/models.html?gpu=1 to enable GPU backend, ?cpu=1 to enable CPU and so forth? This might be useful for quick debugging.

Great idea! Thanks @anssiko .

I added a commit to support a slightly different version of this idea. Instead of using `gpu`, I used `backend` that aligns to tf.js [`setBackend`](https://js.tensorflow.org/api/latest/#setBackend). It accepts `webgl` or `cpu`. If not set, polyfill will use tf.js default backend, e.g. webgl in browser and cpu in node.js. There is a info log in console, e.g. 

```
webnn-polyfill uses tf.js 2.7.0 cpu backend.
```

With that, to reproduce the webgl failures: https://huningxin.github.io/webnn-polyfill/test/models.html?backend=webgl
To reproduce the cpu success: https://huningxin.github.io/webnn-polyfill/test/models.html?backend=cpu

@pyu10055 , hope this helps.

**Comment by anssiko** [comment]
@huningxin thanks for implementing my enhancement idea! I hope it'll help also others debug the tests quickly.

**Comment by huningxin** [comment]
Rebased this PR to the ToT.

By using the `utils.ctsFp32RestrictAccuracyCriteria` (`atol = 1e-5` and `rtol = 5.0 * 1.1920928955078125e-7`), the test results are

 * [cpu backend](https://huningxin.github.io/webnn-polyfill/test/models.html?backend=cpu)
   * squeezenet1.0 nhwc: pass
   * squeezenet1.1 nchw: fail
     * log: actual(8.60241985321045) expected(8.602437973022461) delta(0.00001811981201171875) 
 * [webgl backend](https://huningxin.github.io/webnn-polyfill/test/models.html?backend=webgl)
   * squeezenet1.0 nhwc: fail
     * log: actual(0.0007071918807923794) expected(0.000777950685005635) delta(0.00007075880421325564)
   * squeezenet1.1 nchw: fail
     * log: actual(55.19351577758789) expected(56.4823112487793) delta(1.2887954711914062)

**Comment by wchao1115** [comment]
re: conformance testing

I've added a few considerations for conformance testing in the linked discussion thread from the WebML workshop here for future reference:

https://github.com/w3c/machine-learning-workshop/issues/80#issuecomment-764749028

**Review by pyu10055 — APPROVED** [review]
Thanks Ningxin!

**Comment by huningxin** [comment]
> I've added a few considerations for conformance testing in the linked discussion thread from the WebML workshop here for future reference:
> 
> [w3c/machine-learning-workshop#80 (comment)](https://github.com/w3c/machine-learning-workshop/issues/80#issuecomment-764749028)

@wchao1115 , thanks for your inputs. They are very helpful. With this PR merged, there are both op and model level testing. We'll keep investigating the tolerance settings and report back later.

**Comment by huningxin** [comment]
Thanks for the review and approval, @pyu10055 . I am going to merge this PR.

**Pull request merged**
