### PR TITLE
Drop test directory from NPM package.

### PR DESCRIPTION
**Pull request by BruceDai**
Address feedback on #196.
@Honry  PTAL, thanks.

### CODE REVIEW

**Comment by Honry** [comment]
Thanks @BruceDai, please also add an `.npmignore` file to exclude files that we won't to publish to npm package.

See https://zellwk.com/blog/ignoring-files-from-npm-package/

**Comment by BruceDai** [comment]
Done, thanks @Honry. Please have a try.

**Comment by Honry** [comment]
LGTM, thanks!

**Comment by Honry** [comment]
New version published: https://cdn.jsdelivr.net/npm/@webmachinelearning/webnn-polyfill/, those unnecessary files excluded.

**Comment by BruceDai** [comment]
Awesome. Let's merge it.

**Comment by anssiko** [comment]
Thanks @BruceDai @Honry!

**Pull request merged**
