### PR TITLE
Fix the gru issue for rnnoise example

### PR DESCRIPTION
**Pull request by huningxin**
The root cause is gru use tf.tidy that releases
some intermediate tensors incorrectly.

### CODE REVIEW

**Comment by huningxin** [comment]
@miaobin, please check whether this fixes your rnnoise example. Thanks!

**Comment by miaobin** [comment]
> @miaobin, please check whether this fixes your rnnoise example. Thanks!

OK, I'll check it now.

**Comment by miaobin** [comment]
> > @miaobin, please check whether this fixes your rnnoise example. Thanks!
> 
> OK, I'll check it now.

@huningxin This PR has fixed the compilation issue of rnnoise example. Thanks a lot!

**Comment by huningxin** [comment]
Thanks for verification. As all tests passed, and to unblock the rnnoise example development, I am going to merge this PR.

**Pull request merged**
