### PR TITLE
Support updated spec for third input of gemm op.

### LINKED ISSUE #68: Gemm only support 2D tensor
The third optional operand must be [2D tensor](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm).

Maybe we should remove `gemm scalar bias ` , `gemm single vector bias`  test case, and remove [0.0](https://github.com/webmachinelearning/webnn-polyfill/blob/master/test/ops/gemm.js#L435) for both `gemm aTranspose` and `gemm bTranspose`.

### PR DESCRIPTION
**Pull request by BruceDai**
This pr is to fix #68.

@huningxin PTAL, thanks.

### CODE REVIEW

**Review by huningxin — COMMENTED** [review]
The fix of tests looks good. Could you please also fix the gemm implementation?

**Comment by BruceDai** [comment]
>Could you please also fix the gemm implementation?

Hi @huningxin, The gemm implementation in [src/nn/ops/gemm.ts](https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/gemm.ts) and [MLGemmOptions interface](https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/graph_builder.ts#L91) in src/nn/graph_builder.ts look good. What's your suggestion, thanks.

**Comment by huningxin** [comment]
I mean the implementation should check the 2-D bias and report error if it is not 2-D.

**Comment by BruceDai** [comment]
> I mean the implementation should check the 2-D bias and report error if it is not 2-D.

I tried to check 2-D tensor by `options.c.desc.dimensions.length === 2` condition in [src/nn/ops/gemm.ts](https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/gemm.ts), but an error "_Property 'desc' does not exisit on type 'MLOperand'._" happened, so does it need add a function of getting `desc` attribute in **MLOperand** class? Any suggestion, thanks.

**Comment by huningxin** [comment]
One solution is to reimplement gemm by using tf APIs, so you could check the tensor shape. However, by reviewing the spec again, I think probably we need to allow the `c` to be broadcastable, as it `builder.add` is broadcastable.

**Comment by huningxin** [comment]
Opened https://github.com/webmachinelearning/webnn/issues/171 , let's discuss about the spec before merge this PR.

**Comment by BruceDai** [comment]
OK, thanks @huningxin.

**Comment by huningxin** [comment]
gemm spec https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm supports scalar and broadcast now. Please take a look.

**Comment by BruceDai** [comment]
Thanks @huningxin.
I updated assert checking for third input of gemm and test purpose of broadcasting in the new commit, PTAL, thanks.

**Review by huningxin — APPROVED** [review]
LGTM. Thanks @BruceDai !

**Pull request merged**
