### PR TITLE
Add model tests of TinyYolov2 model.

### PR DESCRIPTION
**Pull request by BruceDai**
Use ctsFp32RestrictAccuracyCriteria(1e-5, 5.0 * 1.1920928955078125e-7) for three model tests of TinyYolov2 nhwc model, these three tests would fail with this error message:
```
  test tinyYolov2 nhwc
a(-9.346943855285645) b(-9.346960067749023) delta(0.00001621246337890625)
    1) test_data_set_0
a(-7.7079949378967285) b(-7.708010673522949) delta(0.000015735626220703125)
    2) test_data_set_1
a(2.4212486743927) b(2.421262264251709) delta(0.000013589859008789062)
    3) test_data_set_2


  0 passing (31s)
  3 failing

  1) test tinyYolov2 nhwc
       test_data_set_0:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testTinyYoloV2 (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:97:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:102:5)

  2) test tinyYolov2 nhwc
       test_data_set_1:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testTinyYoloV2 (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:97:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:108:5)

  3) test tinyYolov2 nhwc
       test_data_set_2:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testTinyYoloV2 (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:97:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:114:5)

```
while use ctsFp32RelaxedAccuracyCriteria(5.0 * 0.0009765625, 5.0 * 0.0009765625), tests would pass. So I use ctsFp32RelaxedAccuracyCriteria for model tests of TinyYolov2 nhwc model in this PR.

@huningxin PTAL, thanks.

### CODE REVIEW

**Comment by huningxin** [comment]
> while use ctsFp32RelaxedAccuracyCriteria(5.0 * 0.0009765625, 5.0 * 0.0009765625), tests would pass. So I use ctsFp32RelaxedAccuracyCriteria for model tests of TinyYolov2 nhwc model in this PR.

Where does the test input and output come from? Could you please specify the tools and steps used?

**Comment by BruceDai** [comment]
> Where does the test input and output come from? Could you please specify the tools and steps used?

According to "**`.npy` files under this folder are downloaded from model of Tiny YOLO v2, which is converted from [YAD2K project](https://github.com/allanzelener/YAD2K)**" on [models/tiny_yolov2_nhwc/README.md](https://github.com/webmachinelearning/test-data/blob/main/models/tiny_yolov2_nhwc/README.md),
, the test data are generated by running TinyYolov2 model based on [YAD2K project](https://github.com/BruceDai/YAD2K/tree/gen_test_data) with [yolov2-tiny-voc.cfg](https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov2-tiny-voc.cfg) and [yolov2-tiny-voc.weights](http://pjreddie.com/media/files/yolov2-tiny-voc.weights).

Details: 

1. input_0.npy and output_0.npy of [tiny_yolov2_nhwc/test_data_set/0](https://github.com/webmachinelearning/test-data/tree/main/models/tiny_yolov2_nhwc/test_data_set/0) is generated by running TinyYolov2 model with [images/dog.jpg](https://github.com/allanzelener/YAD2K/blob/master/images/dog.jpg) 
2. input_0.npy and output_0.npy of [tiny_yolov2_nhwc/test_data_set/1](https://github.com/webmachinelearning/test-data/tree/main/models/tiny_yolov2_nhwc/test_data_set/1) is generated by  running TinyYolov2 model with [images/horses.jpg](https://github.com/allanzelener/YAD2K/blob/master/images/horses.jpg) 
3. input_0.npy and output_0.npy of [tiny_yolov2_nhwc/test_data_set/2](https://github.com/webmachinelearning/test-data/tree/main/models/tiny_yolov2_nhwc/test_data_set/2) is generated by running TinyYolov2 model with [images/person.jpg](https://github.com/allanzelener/YAD2K/blob/master/images/person.jpg) 

Commands to generate test data:
```sh
$ git clone https://github.com/BruceDai/YAD2K && cd YAD2K
$ git checkout gen_test_data
$ python3 test_yolo.py model_data/yolov2-tiny-voc.h5 -a model_data/yolov2-tiny-voc_anchors.txt -c model_data/pascal_classes.txt
```

@huningxin PTAL, thanks.

**Comment by huningxin** [comment]
Thanks for the detailed steps. Could you please add a README.md with this details? With that, we can merge.

**Comment by BruceDai** [comment]
Done by https://github.com/webmachinelearning/test-data/pull/10. @huningxin PTAL, thanks.

**Review by huningxin — APPROVED** [review]

**Pull request merged**
