### PR TITLE
fix matmul 2dX1d and 1dX2d issues

### PR DESCRIPTION
**Pull request by mingmingtasd**
PTAL, thanks! @BruceDai

### CODE REVIEW

**Comment by BruceDai** [comment]
Thanks @mingmingtasd, LGTM.

**Review by huningxin — APPROVED** [review]
LGTM. Thanks @mingmingtasd !

**Comment by huningxin** [comment]
It looks like the polyfill implementation of matmul also needs to be fixed. @BruceDai , could you please take a look?

**Comment by BruceDai** [comment]
OK, thanks @huningxin.

**Comment by BruceDai** [comment]
Thanks @mingmingtasd for reporting this matmul issue of an input as 1-D tensor, I fixed by #71, PTAL.

**Comment by huningxin** [comment]
Thanks @BruceDai ! #71 merged. @mingmingtasd , could we close this PR?

**Pull request closed without merging**
