### PR TITLE
Add model tests of ResNet model.

### PR DESCRIPTION
**Pull request by BruceDai**
Three model tests of ResNet50v2 nchw model all failed with test_data_set converted from sample test data of [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model file.

[ResNet50v2_NCHW_Tests_result_details.xlsx](https://github.com/webmachinelearning/webnn-polyfill/files/6808095/ResNet50v2_NCHW_Tests_result_details.xlsx)

The error message of not satisfying accuracy tolerance, likes:

```
> cross-env NODE_ENV=test mocha --require ./node_setup.js --exit ./test/models/resnet50v2_nchw.js



  test resnet50v2 nchw
a(-21.065582275390625) b(-22.073230743408203) delta(1.0076484680175781)
    1) test_data_set_0
a(-20.56405258178711) b(-20.489290237426758) delta(0.07476234436035156)
    2) test_data_set_1
a(-21.98280906677246) b(-19.088092803955078) delta(2.894716262817383)
    3) test_data_set_2


  0 passing (56s)
  3 failing

  1) test resnet50v2 nchw
       test_data_set_0:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testResNet50V2 (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:181:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:189:5)

  2) test resnet50v2 nchw
       test_data_set_1:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testResNet50V2 (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:181:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:195:5)

  3) test resnet50v2 nchw
       test_data_set_2:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
      at testResNet50V2 (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:181:11)
      at async Context.<anonymous> (file:///path/webnn-polyfill/test/models/resnet50v2_nchw.js:201:5)
``` 

@huningxin PTAL, thanks.

### CODE REVIEW

**Comment by huningxin** [comment]
> Three model tests of ResNet50v2 nchw model all failed with test_data_set converted from sample test data of [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model file.

Where do the test input and output data come from? Which native tool and steps do you use to verify them?

**Comment by BruceDai** [comment]
> Where do the test input and output data come from? Which native tool and steps do you use to verify them?

The test input and output data are converted from **input_0.pb** and **output_0.pb** of three sample test data of [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model file. 
```
resnet50v2
├── test_data_set_0
│   ├── input_0.pb
│   └── output_0.pb
├── test_data_set_1
│   ├── input_0.pb
│   └── output_0.pb
└── test_data_set_2
    ├── input_0.pb
    └── output_0.pb
```

To verify, I implement this simple script **check.py** referring to [run_test_dir method](https://github.com/onnx/models/blob/master/workflow_scripts/ort_test_dir_utils.py#L179) of [onnx/models repo](https://github.com/onnx/models).

Here's the content of **check.py** :
```python3
import glob
from onnx import numpy_helper
import onnx
import onnxruntime as ort
import os
import sys
import numpy as np

def get_data_from_pb(pbfile):
    data = onnx.load_tensor(pbfile)
    data = numpy_helper.to_array(data)
    return data

def check(model_dir):
    onnx_models = glob.glob(os.path.join(model_dir, '*.onnx'))
    sess = ort.InferenceSession(onnx_models[0])
    output_names = [o.name for o in sess.get_outputs()]
    test_dirs = [d for d in glob.glob(os.path.join(model_dir, 'test*')) if os.path.isdir(d)]
    for d in test_dirs:
        print('>> test_data_set: %s' % d)
        inputs = {}
        input_data = get_data_from_pb('%s/input_0.pb' % d)
        inputs['data'] = input_data
        actual = sess.run(output_names, inputs)
        expected = get_data_from_pb('%s/output_0.pb' % d)
        if not np.isclose(expected, actual, rtol=1.e-3, atol=1.e-3).all():
            print('Result: Actual outputs are not as expected, FAIL...')
        else:
            print('Result: Actual outputs are as expected, PASS...')

if __name__ == '__main__':
    check(sys.argv[1])
```

to run this script, prepare to download [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model file and extract resnet50-v2-7.tar.gz to /your-path folder,  install numpy, onnx and onnxruntime with pip3, then run this command
```sh
python3 check.py /your-path/resnet50v2
```

output messages like:
```
>> test_data_set: /tmp/resnet50v2/test_data_set_0
Result: Actual outputs are as expected, PASS...
>> test_data_set: /tmp/resnet50v2/test_data_set_2
Result: Actual outputs are as expected, PASS...
>> test_data_set: /tmp/resnet50v2/test_data_set_1
Result: Actual outputs are as expected, PASS...
```

@huningxin PTAL, thanks.

**Comment by huningxin** [comment]
Thanks for the details. It looks like an implementation issue of webnn-polyfill since ONNXRuntime can pass the test.

How about WebNN-native, say OpenVINO and DirectML backends?

**Comment by BruceDai** [comment]
> How about WebNN-native, say OpenVINO and DirectML backends?

About WebNN-native with DirectML backend, there's an issue **[DML] ResNet NCHW model tests doesn't meet the tolerance requirement** https://github.com/webmachinelearning/webnn-native/issues/23, and WebNN-native with OpenVINO backend, these three model tests would pass with criteria as [tolerance < 0.005](https://github.com/webmachinelearning/webnn-native/blob/main/examples/SampleUtils.cpp#L48), thanks.

**Comment by huningxin** [comment]
> About WebNN-native with DirectML backend, there's an issue **[DML] ResNet NCHW model tests doesn't meet the tolerance requirement** [webmachinelearning/webnn-native#23](https://github.com/webmachinelearning/webnn-native/issues/23),

It would be helpful if it could compare with ONNXRuntime DirectML backend. Do you happen to test against that?

**Comment by BruceDai** [comment]
Hi @huningxin, I ran [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model test by [ONNX Runtime](https://github.com/microsoft/onnxruntime) using DirectML backend (execution provider), here's test result, PTAL, thanks.

|Device|GPU|GPU Driver Version|Test Result|
|----|----|----|----|
| ASUS ZenBook Flip S  laptop | Intel Xe Graphics | 27.20.100.9565 | FAIL |
| ASUS ZenBook Flip S  laptop | Intel Xe Graphics | 30.0.100.9684 | PASS |
| Desktop | Nvidia GeForce GTX 1080 | 27.21.14.5671 | PASS |

**Comment by huningxin** [comment]
@BruceDai , thanks for your validation on ONNX Runtime, it proves the test data is good on native. So please help file issues to webnn-polyfill and webnn-native according to this issue. Then we'll merge this PR and it would help developers to fix the corresponding issues. WDYT?

**Comment by BruceDai** [comment]
Thanks @huningxin. I filed issue #105 to this webnn-polyfill repo, and there's already https://github.com/webmachinelearning/webnn-native/issues/23 to webnn-native repo.

**Comment by huningxin** [comment]
Thanks @BruceDai , merging.

**Pull request merged**
