### PR TITLE
Change file names to lowercases

### LINKED ISSUE #5: Build fails on Linux
The root cause is that some file names have capital characters but the import statements assume lowercase. This is fine to build on Windows. But it fails on Linux.

### PR DESCRIPTION
**Pull request by huningxin**
Fix #5

### CODE REVIEW

**Comment by huningxin** [comment]
@BruceDai could you please help verify this fix? Thanks!

**Comment by BruceDai** [comment]
@huningxin I verified this PR, it works well, thanks.

**Comment by BruceDai** [comment]
@huningxin Updated the above comment with details.
I verified this PR on both Linux (Ubuntu 18.04.4 LTS) and Windows (Windows 10 HOME/Version 1909/OS build 18363.1082) platforms, Node : Latest LTS Version (12.18.4)[https://nodejs.org/en/download/]

Following [Build & Test guideline of README](https://github.com/webmachinelearning/webnn-polyfill#build-and-test) , I built and tested with this PR's source code, the issue #5 couldn't be reproduced on Linux, both build were successful on Linux and Windows platforms, and here're results by running tests in node.js and web browser (using Chrome stable 85.0.4183.102), all tests pass.

test |  Linux | Windows
---- | ---- | ----
in node.js | 34/34 pass | 34/34 pass
in web browser |34/34 pass | 34/34 pass

**Comment by huningxin** [comment]
@BruceDai , that's very helpful. Thanks for your efforts!

@anssiko , as there is no code change and Bruce helped verify the fix, do you think we can merge this PR?

**Comment by anssiko** [comment]
Yes, please go ahead and merge. Thanks!

**Pull request merged**
