### PR TITLE
Add conv2d CTS test with fused operations.

### LINKED ISSUE #99: Support/update CTS tests with fused activation/bias function.

### PR DESCRIPTION
**Pull request by BruceDai**
Add 76 conv2d CTS test with fused operations, fix #99. 
@huningxin PTAL, thanks.

### CODE REVIEW

**Review by huningxin — COMMENTED** [review]
@BruceDai , thanks for the PR. However, I couldn't find any usage of fused bias. And all the fused activation is just `builder.clamp()`, I couldn't find the fused activations of `relu` and `relu6`. Did I miss anything?

**Comment by BruceDai** [comment]
@huningxin Thanks for your review.

>  However, I couldn't find any usage of fused bias.

For example, on https://github.com/webmachinelearning/webnn-polyfill/blob/074460cf20469efa06c8de540a848c92b68ac772/test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float.js#L18
```js
    const op3 = builder.constant({type: 'float32', dimensions: [1]}, new Float32Array([0]));
    const pad0 = 0;
    const stride = 1;
    const expected = [0.875, 0.875, 0.875, 0.875];
    const op4 = builder.conv2d(op1, op2, {'bias': op3, 'padding': [pad0, pad0, pad0, pad0], 'strides': [stride, stride], 'inputLayout': 'nhwc', 'filterLayout': 'ohwi', 'activation': builder.clamp()});
```
the bais is also fused.

>  And all the fused activation is just builder.clamp(), I couldn't find the fused activations of relu and relu6. 

Current these CTS tests are automatically generated by scripts, and NNAPI CONV_2D/DEPTHWISE_CONV_2D CTS tests only use none fuse, so tests don't include fused activations of relu and relu6. 

DO you suggest me adding some conv2d CTS tests with fused activations of relu and relu6 manually? Thanks.

**Comment by huningxin** [comment]
> the bais is also fused.

That's good. I missed that.

> NNAPI CONV_2D/DEPTHWISE_CONV_2D CTS tests only use none fuse, so tests don't include fused activations of relu and relu6.

Then it should just not set the `activation`.

**Comment by BruceDai** [comment]
Updated. Please take another look, thanks. @huningxin

**Review by huningxin — APPROVED** [review]
LGTM. Thanks @BruceDai !

**Pull request merged**
