### PR TITLE
Implement ops for style transfer model

### LINKED ISSUE #34: Implement the changes/additions of ops for style transfer models
Implement the spec change of https://github.com/webmachinelearning/webnn/pull/123.

The changes include:
> - Extend the `conv2d` operation to support transposed convolution, an essential upsample tool for encoder-decoder models.
> - Add `instanceNormalization` in addition to batch-normalization. Instance-normalization is a fused operation for a normalization subgraph that computes the mean and variance values per-feature instance on the fly.
> - Replace the `sqrt` unary operation with a more generic `pow` binary operation used by the normalization process.
> - Add `pad` operation that supports all 4 padding modes found in various frameworks.
> - Add `resample` operation to support both upsampling and downsampling of feature instances. This operation is used in the ONNX version of the style-transfer models.

### PR DESCRIPTION
**Pull request by huningxin**
fix #34 

@BruceDai , PTAL. As this PR includes the API change of conv2d and pool2d, the cts needs to be fixed. Please help fix them. I excluded the cts in the npm test script. Once you fix the cts, please re-include them.

@Honry please also take a look from style transfer sample perspective. 

Thanks!

### CODE REVIEW

**Comment by BruceDai** [comment]
> the cts needs to be fixed. Please help fix them. I excluded the cts in the npm test script. Once you fix the cts, please re-include them.

@huningxin Yes, I will fix cts part, thanks.

**Review by BruceDai — APPROVED** [review]
Thanks @huningxin, LGTM. 

I verified this pr, all 431 tests passed by running in node.js and in Chrome browser.

**Comment by huningxin** [comment]
@BruceDai I also fixed the build-docs script according to typedoc dependency update. And similar to https://github.com/webmachinelearning/webnn/pull/151, I also fixed this repo. Please take another look.

**Comment by huningxin** [comment]
cc @anssiko

**Review by anssiko — APPROVED** [review]
🚀

**Comment by Honry** [comment]
@huningxin, thanks! LGTM, all ops that required by style transfer sample have been included in this PR.

**Comment by BruceDai** [comment]
> @BruceDai I also fixed the build-docs script according to typedoc dependency update. And similar to [webmachinelearning/webnn#151](https://github.com/webmachinelearning/webnn/pull/151), I also fixed this repo. Please take another look.

@huningxin LGTM, thanks.

**Comment by huningxin** [comment]
Thanks for the review. Let's merge it and unlock the development of style transfer sample.

**Pull request merged**
