### PR TITLE
Implement activation functions as fused operators to BatchNorm, Conv2d, gru and gruCell

### LINKED ISSUE #92: Implement activation functions as fused operators to BatchNorm, Conv2d, gru and gruCell
Implement the spec change introduced by https://github.com/webmachinelearning/webnn/pull/188

### PR DESCRIPTION
**Pull request by huningxin**
fix #92

### CODE REVIEW

**Comment by huningxin** [comment]
@BruceDai , please take a look. Thanks.

**Comment by BruceDai** [comment]
Thanks much @huningxin.

> Need to add fused conv2d tests in CTS as well.

I filed #99 to track this task.

> Need to test fused conv2d and batchNorm of ResNet tests.

I double checked that all tests passed both in node.js by CPU backend and in web browser by WebGL backend, and such fused tests also passed in web browser by WASM backend with no regression, thanks.

**Review by BruceDai — APPROVED** [review]

**Comment by Honry** [comment]
> @Honry , please also take a look from samples perspective:

> 1. Need to check whether gru and gruCell usage of activations, there are API changes

Only nsnet2 use `gru` op, but which has no `activations` attribute.

> 2. Optimize the performance of conv2d and batchNorm by using fused bias and activations.

I will update all `conv2d` and `batchNorm` to use fused bias and activations.

**Comment by huningxin** [comment]
@BruceDai , thanks for your verification. It is very helpful.

@Honry , thanks for your confirmation. So `gru` should just work with the default activations. The current non-fused conv2d and batchNorm should still work. So this PR should not break anything.

With that, I am going to merge this PR.

**Pull request merged**
